### ISSUE TITLE
nvim backend result is empty

### ISSUE THREAD

**Issue by wzrdtales** [eugen0329/vim-esearch#184] opened 2021-06-15 17:08 UTC
Since the last time I ran a plugin upgrade the nvim backend now returns empty. When I change to system it will return an out.

my version: v0.5.0-dev+1415-g19ccda230

**Comment by wzrdtales** [comment] 2021-06-15 17:15
seems like it is releated to neovim i only loaded esearch and tried different old versions, but the result list stays empty with the nvim backend.

**Comment by wzrdtales** [comment] 2021-06-15 17:17
ok also not neovim releated downgraded to neovim 0.4.4 once to see

**Comment by wzrdtales** [comment] 2021-06-15 17:32
so not sure what is wrong, it immediately returns an emtpy search result on nvim backend now.

**Comment by wzrdtales** [comment] 2021-06-15 17:46
let me know what I can do to deliver the information needed to figure out what the bug is about

**Comment by eugen0329** [comment] 2021-06-15 17:58
Hello. Thanks for your report.

Can you try to reproduce it with the latest [neovim build](https://github.com/neovim/neovim/releases/tag/nightly) and a minimal vimrc configuration, please?
```vim
" /tmp/vimrc
if !filereadable('/tmp/vim/autoload/plug.vim')
  exe 'silent !mkdir -p /tmp/vim/autoload && curl -fLo /tmp/vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
endif
set runtimepath+=/tmp/vim
call plug#begin('/tmp/vim/bundle')
Plug 'eugen0329/vim-esearch'
call plug#end()
PlugInstall | q
filetype plugin indent on
```
Run it using `nvim -u /tmp/vimrc` and let me know if it works.

**Comment by wzrdtales** [comment] 2021-06-15 18:01
I am already on the latest neovim build. Tried with that config, still searches nothing, and immediately returns ```Matches in 0 lines, 0 files. Finished.```

**Comment by wzrdtales** [comment] 2021-06-15 18:01
messages is empty as well so no error message unfortunately.

**Comment by eugen0329** [comment] 2021-06-15 18:06
After the search is finished, run the following command within the search buffer and send me the output:

```vim
echo [g:esearch.adapter, g:esearch.backend, b:esearch.cwd, b:esearch.adapter, b:esearch.backend, b:esearch.request.command, b:esearch.request.data[:3]]
```

**NOTE** the output may contain some of your search results. Make sure to not accidentally leak your private data.

**Comment by wzrdtales** [comment] 2021-06-15 18:08
```
['rg', 'nvim', '/home/tobi/censored', 'rg', 'nvim', 'rg --fixed-strings  --ignore-case --no-heading --color=never --line-number --with-filename --follow   -e  ''redis'' -- ', []]
```

**Comment by eugen0329** [comment] 2021-06-15 18:23
What `rg --version` returns?

**Comment by wzrdtales** [comment] 2021-06-15 18:32
```
ripgrep 13.0.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```

**Comment by wzrdtales** [comment] 2021-06-15 18:49
I just looked (using arch) if I have the last version of ripgrep installed since you asked. 12.1.1 was still there and I tried a downgrade on that once. So the culprit is the latest ripgrep then, 12.1.1 works.

**Comment by eugen0329** [comment] 2021-06-15 19:09
Reproduced with rg 13.0.0. I'll investigate the problem, thanks.

**Comment by eugen0329** [comment] 2021-06-16 21:56
You can use a workaround like `let g:esearch = {'adapter': 'ag'}` or `let g:esearch = {'adapter': 'grep'}` for now.

There is a solution to allocate a pty, but it'll kill the performance because of updates on the search input text change.
I'm going to investigate more and will release a fix for `rg`, but it'll be in around a week.

**Comment by wzrdtales** [comment] 2021-06-16 23:09
I rather downgrade than loosing time :sweat: , take your time knowing i just need to downgrade for the meantime is not a big deal for me.

**Comment by eugen0329** [comment] 2021-06-25 21:55
I've pushed the fix. Can you update the plugin and let me know if there're still any problems, please?

**Closed by eugen0329** 2021-06-25 21:55 UTC

**Comment by wzrdtales** [comment] 2021-06-28 10:32
works perfectly again :)
